# COVAR5 = model.covariances_
# COVAR4_norm = np.linalg.norm(COVAR4)
# COVAR5_norm = np.linalg.norm(COVAR5)
# COVARQYS = (COVAR1+COVAR2+COVAR3)/3
# COVARQYS_norm = np.linalg.norm(COVARQYS)
# cos123and4 = np.dot(COVARQYS, COVAR4) / (COVARQYS_norm * COVAR4_norm)
# cos123and001 = np.dot(COVARQYS, COVAR5) / (COVARQYS_norm * COVAR5_norm)
# print(cos123and4)
# print(cos123and001)

# COVAR1_norm = np.linalg.norm(COVAR1)
# COVAR2_norm = np.linalg.norm(COVAR2)
# COVAR3_norm = np.linalg.norm(COVAR3)
# COVAR4_norm = np.linalg.norm(COVAR4)
# COVAR5_norm = np.linalg.norm(COVAR5)
# dif12 = np.sqrt(np.sum(np.square(MEAN1 - MEAN2)))
# dif13 = np.sqrt(np.sum(np.square(MEAN1 - MEAN3)))
# dif14 = np.sqrt(np.sum(np.square(MEAN1 - MEAN4)))
# dif15 = np.sqrt(np.sum(np.square(MEAN1 - MEAN5)))
# print("MEAN")
# print(dif12)
# print(dif13)
# print(dif14)
# print(dif15)
#
# cos12 = np.dot(COVAR1, COVAR2) / (COVAR1_norm * COVAR2_norm)
# cos13 = np.dot(COVAR1, COVAR3) / (COVAR1_norm * COVAR3_norm)
# cos14 = np.dot(COVAR1, COVAR4) / (COVAR1_norm * COVAR4_norm)
# cos15 = np.dot(COVAR1, COVAR5) / (COVAR1_norm * COVAR5_norm)
# print("COS")
# print(cos12)
# print(cos13)
# print(cos14)
# print(cos15)